spring.application.name=SELATTENDANCE
spring.datasource.url=jdbc:h2:mem:selattendance;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.uniauth.url=jdbc:h2:mem:uniauth;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.uniauth.driver-class-name=org.h2.Driver
spring.datasource.uniauth.username=sa
spring.datasource.uniauth.password=
spring.sql.init.mode=never
mybatis.mapper-locations=classpath*:/com/sp/selfsp/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
uniauth.jwt.secret=SELATTENDANCE-UNIAUTH-SECRET-2026
uniauth.jwt.expire-seconds=7200
server.port=8090
