CREATE TABLE IF NOT EXISTS tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    contact_name VARCHAR(100),
    contact_phone VARCHAR(50),
    contact_email VARCHAR(100),
    timezone VARCHAR(50) DEFAULT 'Asia/Tokyo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_code VARCHAR(50) NOT NULL,
    workplace_name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_workplace_code UNIQUE (tenant_id, workplace_code)
);

CREATE TABLE IF NOT EXISTS department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    parent_id BIGINT,
    department_code VARCHAR(50),
    department_name VARCHAR(200) NOT NULL,
    sort_order INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    department_id BIGINT,
    employee_no VARCHAR(50) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    employee_name_kana VARCHAR(100),
    gender VARCHAR(20),
    employment_type VARCHAR(30) NOT NULL,
    hire_date DATE,
    resign_date DATE,
    email VARCHAR(100),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_no UNIQUE (tenant_id, employee_no)
);

CREATE TABLE IF NOT EXISTS employee_work_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_rule_type VARCHAR(30) NOT NULL,
    standard_daily_minutes INT NOT NULL,
    standard_weekly_minutes INT NOT NULL,
    overtime_enabled TINYINT DEFAULT 1,
    night_work_enabled TINYINT DEFAULT 0,
    holiday_work_enabled TINYINT DEFAULT 0,
    rounding_rule_id BIGINT,
    effective_start_date DATE NOT NULL,
    effective_end_date DATE
);

CREATE TABLE IF NOT EXISTS employee_external_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    external_employee_id VARCHAR(100) NOT NULL,
    external_employee_no VARCHAR(100) NOT NULL,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shift_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    template_code VARCHAR(50) NOT NULL,
    template_name VARCHAR(200) NOT NULL,
    shift_type VARCHAR(30) NOT NULL,
    start_time VARCHAR(20),
    end_time VARCHAR(20),
    cross_day TINYINT DEFAULT 0,
    scheduled_break_minutes INT DEFAULT 0,
    color VARCHAR(30),
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_template_code UNIQUE (tenant_id, template_code)
);

CREATE TABLE IF NOT EXISTS shift_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    shift_template_id BIGINT,
    scheduled_start_time TIMESTAMP,
    scheduled_end_time TIMESTAMP,
    scheduled_break_minutes INT DEFAULT 0,
    work_day_type VARCHAR(30) DEFAULT 'WORKDAY',
    status VARCHAR(30) DEFAULT 'ACTIVE',
    locked TINYINT DEFAULT 0,
    remark VARCHAR(500),
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_work_date UNIQUE (tenant_id, employee_id, work_date)
);

CREATE TABLE IF NOT EXISTS punch_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source_system VARCHAR(50),
    import_type VARCHAR(30),
    file_name VARCHAR(300),
    total_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    duplicate_count INT DEFAULT 0,
    unmatched_count INT DEFAULT 0,
    error_count INT DEFAULT 0,
    ignored_count INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'PROCESSING',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS punch_source_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    config_name VARCHAR(100),
    api_base_url VARCHAR(500),
    api_key VARCHAR(500),
    api_secret VARCHAR(500),
    webhook_secret VARCHAR(500),
    enabled TINYINT DEFAULT 1,
    config_json CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_source_system UNIQUE (tenant_id, source_system)
);

CREATE TABLE IF NOT EXISTS punch_raw_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT,
    external_employee_id VARCHAR(100),
    source_system VARCHAR(50) NOT NULL,
    source_event_id VARCHAR(100),
    punch_time TIMESTAMP NOT NULL,
    punch_type VARCHAR(30) NOT NULL,
    device_id VARCHAR(100),
    device_name VARCHAR(200),
    raw_payload CLOB,
    import_batch_id BIGINT,
    process_status VARCHAR(30) DEFAULT 'PENDING',
    error_message VARCHAR(500),
    ignored_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_source_event UNIQUE (tenant_id, source_system, source_event_id)
);

CREATE TABLE IF NOT EXISTS attendance_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    shift_schedule_id BIGINT,
    work_day_type VARCHAR(30) DEFAULT 'WORKDAY',
    scheduled_start_time TIMESTAMP,
    scheduled_end_time TIMESTAMP,
    scheduled_break_minutes INT DEFAULT 0,
    scheduled_work_minutes INT DEFAULT 0,
    actual_clock_in TIMESTAMP,
    actual_clock_out TIMESTAMP,
    actual_break_minutes INT DEFAULT 0,
    actual_work_minutes INT DEFAULT 0,
    late_minutes INT DEFAULT 0,
    early_leave_minutes INT DEFAULT 0,
    absence_minutes INT DEFAULT 0,
    normal_work_minutes INT DEFAULT 0,
    overtime_minutes INT DEFAULT 0,
    legal_overtime_minutes INT DEFAULT 0,
    night_work_minutes INT DEFAULT 0,
    holiday_work_minutes INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'NORMAL',
    approval_status VARCHAR(30) DEFAULT 'NONE',
    exception_flag TINYINT DEFAULT 0,
    locked TINYINT DEFAULT 0,
    calculated_at TIMESTAMP,
    calc_version VARCHAR(50),
    calc_message VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_daily UNIQUE (tenant_id, employee_id, work_date)
);

CREATE TABLE IF NOT EXISTS attendance_exception (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    attendance_daily_id BIGINT,
    exception_type VARCHAR(50) NOT NULL,
    exception_level VARCHAR(30) DEFAULT 'WARN',
    status VARCHAR(30) DEFAULT 'OPEN',
    message VARCHAR(500),
    suggested_action VARCHAR(100),
    resolved TINYINT DEFAULT 0,
    resolved_by BIGINT,
    resolved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_calc_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    attendance_daily_id BIGINT,
    trigger_type VARCHAR(30) NOT NULL,
    trigger_ref_id BIGINT,
    calc_status VARCHAR(30) NOT NULL,
    step_name VARCHAR(100) NOT NULL,
    step_message VARCHAR(1000),
    payload_json CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
