CREATE TABLE IF NOT EXISTS tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    contact_name VARCHAR(100),
    contact_phone VARCHAR(50),
    contact_email VARCHAR(100),
    timezone VARCHAR(50) DEFAULT 'Asia/Tokyo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_code VARCHAR(50) NOT NULL,
    workplace_name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_workplace_code UNIQUE (tenant_id, workplace_code)
);

CREATE TABLE IF NOT EXISTS department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    parent_id BIGINT,
    department_code VARCHAR(50),
    department_name VARCHAR(200) NOT NULL,
    sort_order INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    department_id BIGINT,
    employee_no VARCHAR(50) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    employee_name_kana VARCHAR(100),
    gender VARCHAR(20),
    employment_type VARCHAR(30) NOT NULL,
    hire_date DATE,
    resign_date DATE,
    email VARCHAR(100),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_no UNIQUE (tenant_id, employee_no)
);

CREATE TABLE IF NOT EXISTS employee_work_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_rule_type VARCHAR(30) NOT NULL,
    standard_daily_minutes INT NOT NULL,
    standard_weekly_minutes INT NOT NULL,
    overtime_enabled TINYINT DEFAULT 1,
    night_work_enabled TINYINT DEFAULT 0,
    holiday_work_enabled TINYINT DEFAULT 0,
    rounding_rule_id BIGINT,
    effective_start_date DATE NOT NULL,
    effective_end_date DATE
);

CREATE TABLE IF NOT EXISTS employee_external_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    external_employee_id VARCHAR(100) NOT NULL,
    external_employee_no VARCHAR(100) NOT NULL,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shift_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    template_code VARCHAR(50) NOT NULL,
    template_name VARCHAR(200) NOT NULL,
    shift_type VARCHAR(30) NOT NULL,
    start_time VARCHAR(20),
    end_time VARCHAR(20),
    cross_day TINYINT DEFAULT 0,
    scheduled_break_minutes INT DEFAULT 0,
    color VARCHAR(30),
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_template_code UNIQUE (tenant_id, template_code)
);
