CREATE TABLE IF NOT EXISTS ua_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    tenant_status VARCHAR(30) NOT NULL DEFAULT 'enabled',
    contact_name VARCHAR(100),
    contact_email VARCHAR(100),
    contact_phone VARCHAR(50),
    expire_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    login_name VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    display_name_kana VARCHAR(100),
    locale VARCHAR(20) DEFAULT 'zh-CN',
    email VARCHAR(100),
    phone VARCHAR(50),
    user_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    locked_flag TINYINT DEFAULT 0,
    expired_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    role_code VARCHAR(100) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    role_desc VARCHAR(300),
    builtin_flag TINYINT DEFAULT 0,
    role_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR(50) NOT NULL UNIQUE,
    module_name VARCHAR(100) NOT NULL,
    module_type VARCHAR(30) NOT NULL DEFAULT 'business',
    module_desc VARCHAR(300),
    entry_project VARCHAR(50),
    owner_system VARCHAR(50),
    route_key VARCHAR(120),
    enabled_flag TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR(50) NOT NULL,
    menu_code VARCHAR(100) NOT NULL UNIQUE,
    parent_id BIGINT,
    menu_type VARCHAR(30) NOT NULL,
    route_path VARCHAR(200),
    component_name VARCHAR(200),
    icon_name VARCHAR(100),
    sort_order INT DEFAULT 0,
    title_zh VARCHAR(100) NOT NULL,
    title_ja VARCHAR(100) NOT NULL,
    enabled_flag TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code VARCHAR(50) NOT NULL,
    permission_code VARCHAR(100) NOT NULL UNIQUE,
    permission_name VARCHAR(100) NOT NULL,
    permission_type VARCHAR(30) NOT NULL,
    resource_key VARCHAR(100),
    action_key VARCHAR(100),
    scope_type VARCHAR(30),
    enabled_flag TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    effective_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ua_role_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ua_role_data_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    module_code VARCHAR(50) NOT NULL,
    scope_type VARCHAR(30) NOT NULL,
    scope_value VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ua_login_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token_hash VARCHAR(255) NOT NULL,
    device_info VARCHAR(200),
    login_ip VARCHAR(50),
    expire_at TIMESTAMP NOT NULL,
    revoked_flag TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ua_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    operator_user_id BIGINT,
    operator_name VARCHAR(100),
    module_code VARCHAR(50),
    action_type VARCHAR(50),
    target_type VARCHAR(50),
    target_id VARCHAR(100),
    result_status VARCHAR(30),
    request_path VARCHAR(200),
    detail_text VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
