DROP TABLE IF EXISTS employee_external_mapping;
DROP TABLE IF EXISTS employee_work_rule;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS workplace;
DROP TABLE IF EXISTS shift_template;
DROP TABLE IF EXISTS tenant;

CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    contact_name VARCHAR(100),
    contact_phone VARCHAR(50),
    contact_email VARCHAR(100),
    timezone VARCHAR(50) DEFAULT 'Asia/Tokyo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_code VARCHAR(50) NOT NULL,
    workplace_name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_workplace_code UNIQUE (tenant_id, workplace_code)
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    parent_id BIGINT,
    department_code VARCHAR(50),
    department_name VARCHAR(200) NOT NULL,
    sort_order INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    department_id BIGINT,
    employee_no VARCHAR(50) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    employee_name_kana VARCHAR(100),
    gender VARCHAR(20),
    employment_type VARCHAR(30) NOT NULL,
    hire_date DATE,
    resign_date DATE,
    email VARCHAR(100),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_no UNIQUE (tenant_id, employee_no)
);

CREATE TABLE employee_work_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_rule_type VARCHAR(30) NOT NULL,
    standard_daily_minutes INT NOT NULL,
    standard_weekly_minutes INT NOT NULL,
    overtime_enabled TINYINT DEFAULT 1,
    night_work_enabled TINYINT DEFAULT 0,
    holiday_work_enabled TINYINT DEFAULT 0,
    rounding_rule_id BIGINT,
    effective_start_date DATE NOT NULL,
    effective_end_date DATE
);

CREATE TABLE employee_external_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    external_employee_id VARCHAR(100) NOT NULL,
    external_employee_no VARCHAR(100) NOT NULL,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shift_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    template_code VARCHAR(50) NOT NULL,
    template_name VARCHAR(200) NOT NULL,
    shift_type VARCHAR(30) NOT NULL,
    start_time VARCHAR(20),
    end_time VARCHAR(20),
    cross_day TINYINT DEFAULT 0,
    scheduled_break_minutes INT DEFAULT 0,
    color VARCHAR(30),
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_template_code UNIQUE (tenant_id, template_code)
);

INSERT INTO tenant (
    id, tenant_code, tenant_name, status, contact_name, contact_phone, contact_email, timezone
) VALUES
(1, 'TENANT_DEMO', '东京第一教室', 'ACTIVE', '佐藤美咲', '03-1234-5678', 'admin@tokyo-school.jp', 'Asia/Tokyo');

INSERT INTO workplace (
    id, tenant_id, workplace_code, workplace_name, address, phone, status
) VALUES
(1, 1, 'TKY-HQ', '东京本部', '東京都千代田区1-1-1', '03-1000-1000', 'ACTIVE'),
(2, 1, 'YKH-CLS', '横滨教室', '神奈川県横浜市2-2-2', '045-200-2000', 'ACTIVE');

INSERT INTO department (
    id, tenant_id, workplace_id, parent_id, department_code, department_name, sort_order, status
) VALUES
(1, 1, 1, NULL, 'ADMIN', '管理部', 1, 'ACTIVE'),
(2, 1, 2, NULL, 'YKH-OPS', '横滨运营组', 2, 'ACTIVE');

INSERT INTO employee (
    id, tenant_id, workplace_id, department_id, employee_no, employee_name, employee_name_kana,
    gender, employment_type, hire_date, resign_date, email, phone, status
) VALUES
(1, 1, 1, 1, 'E0001', '山田太郎', 'ヤマダタロウ', 'MALE', 'FULL_TIME', DATE '2026-04-01', NULL, 'taro.yamada@example.jp', '090-1111-1111', 'ACTIVE');
