DROP TABLE IF EXISTS punch_raw_log;
DROP TABLE IF EXISTS punch_import_batch;
DROP TABLE IF EXISTS punch_source_config;
DROP TABLE IF EXISTS shift_schedule;
DROP TABLE IF EXISTS employee_external_mapping;
DROP TABLE IF EXISTS employee_work_rule;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS workplace;
DROP TABLE IF EXISTS shift_template;
DROP TABLE IF EXISTS tenant;

CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(50) NOT NULL UNIQUE,
    tenant_name VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    contact_name VARCHAR(100),
    contact_phone VARCHAR(50),
    contact_email VARCHAR(100),
    timezone VARCHAR(50) DEFAULT 'Asia/Tokyo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_code VARCHAR(50) NOT NULL,
    workplace_name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_workplace_code UNIQUE (tenant_id, workplace_code)
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    parent_id BIGINT,
    department_code VARCHAR(50),
    department_name VARCHAR(200) NOT NULL,
    sort_order INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    workplace_id BIGINT,
    department_id BIGINT,
    employee_no VARCHAR(50) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    employee_name_kana VARCHAR(100),
    gender VARCHAR(20),
    employment_type VARCHAR(30) NOT NULL,
    hire_date DATE,
    resign_date DATE,
    email VARCHAR(100),
    phone VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_no UNIQUE (tenant_id, employee_no)
);

CREATE TABLE employee_work_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_rule_type VARCHAR(30) NOT NULL,
    standard_daily_minutes INT NOT NULL,
    standard_weekly_minutes INT NOT NULL,
    overtime_enabled TINYINT DEFAULT 1,
    night_work_enabled TINYINT DEFAULT 0,
    holiday_work_enabled TINYINT DEFAULT 0,
    rounding_rule_id BIGINT,
    effective_start_date DATE NOT NULL,
    effective_end_date DATE
);

CREATE TABLE employee_external_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    external_employee_id VARCHAR(100) NOT NULL,
    external_employee_no VARCHAR(100) NOT NULL,
    status VARCHAR(30) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shift_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    template_code VARCHAR(50) NOT NULL,
    template_name VARCHAR(200) NOT NULL,
    shift_type VARCHAR(30) NOT NULL,
    start_time VARCHAR(20),
    end_time VARCHAR(20),
    cross_day TINYINT DEFAULT 0,
    scheduled_break_minutes INT DEFAULT 0,
    color VARCHAR(30),
    is_active TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_template_code UNIQUE (tenant_id, template_code)
);

CREATE TABLE shift_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    shift_template_id BIGINT,
    scheduled_start_time TIMESTAMP,
    scheduled_end_time TIMESTAMP,
    scheduled_break_minutes INT DEFAULT 0,
    work_day_type VARCHAR(30) DEFAULT 'WORKDAY',
    status VARCHAR(30) DEFAULT 'ACTIVE',
    locked TINYINT DEFAULT 0,
    remark VARCHAR(500),
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_employee_work_date UNIQUE (tenant_id, employee_id, work_date)
);

CREATE TABLE punch_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source_system VARCHAR(50),
    import_type VARCHAR(30),
    file_name VARCHAR(300),
    total_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    duplicate_count INT DEFAULT 0,
    unmatched_count INT DEFAULT 0,
    error_count INT DEFAULT 0,
    ignored_count INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'PROCESSING',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE punch_source_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    config_name VARCHAR(100),
    api_base_url VARCHAR(500),
    api_key VARCHAR(500),
    api_secret VARCHAR(500),
    webhook_secret VARCHAR(500),
    enabled TINYINT DEFAULT 1,
    config_json CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_source_system UNIQUE (tenant_id, source_system)
);

CREATE TABLE punch_raw_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    employee_id BIGINT,
    external_employee_id VARCHAR(100),
    source_system VARCHAR(50) NOT NULL,
    source_event_id VARCHAR(100),
    punch_time TIMESTAMP NOT NULL,
    punch_type VARCHAR(30) NOT NULL,
    device_id VARCHAR(100),
    device_name VARCHAR(200),
    raw_payload CLOB,
    import_batch_id BIGINT,
    process_status VARCHAR(30) DEFAULT 'PENDING',
    error_message VARCHAR(500),
    ignored_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tenant_source_event UNIQUE (tenant_id, source_system, source_event_id)
);

INSERT INTO tenant (
    id, tenant_code, tenant_name, status, contact_name, contact_phone, contact_email, timezone
) VALUES
(1, 'TENANT_DEMO', '東京第一スクール', 'ACTIVE', '佐藤美咲', '03-1234-5678', 'admin@tokyo-school.jp', 'Asia/Tokyo');

INSERT INTO workplace (
    id, tenant_id, workplace_code, workplace_name, address, phone, status
) VALUES
(1, 1, 'TKY-HQ', '東京本部', '東京都千代田区丸の内1-1-1', '03-1000-1000', 'ACTIVE'),
(2, 1, 'YKH-CLS', '横浜教室', '神奈川県横浜市西区みなとみらい2-2-2', '045-200-2000', 'ACTIVE');

INSERT INTO department (
    id, tenant_id, workplace_id, parent_id, department_code, department_name, sort_order, status
) VALUES
(1, 1, 1, NULL, 'ADMIN', '管理部', 1, 'ACTIVE'),
(2, 1, 2, NULL, 'YKH-OPS', '横浜運営チーム', 2, 'ACTIVE');

INSERT INTO employee (
    id, tenant_id, workplace_id, department_id, employee_no, employee_name, employee_name_kana,
    gender, employment_type, hire_date, resign_date, email, phone, status
) VALUES
(1, 1, 1, 1, 'E0001', '山田太郎', 'ヤマダタロウ', 'MALE', 'FULL_TIME', DATE '2026-04-01', NULL, 'taro.yamada@example.jp', '090-1111-1111', 'ACTIVE');

INSERT INTO employee_work_rule (
    id, tenant_id, employee_id, work_rule_type, standard_daily_minutes, standard_weekly_minutes,
    overtime_enabled, night_work_enabled, holiday_work_enabled, rounding_rule_id,
    effective_start_date, effective_end_date
) VALUES
(1, 1, 1, 'STANDARD', 480, 2400, 1, 1, 1, NULL, DATE '2026-04-01', NULL);

INSERT INTO employee_external_mapping (
    id, tenant_id, employee_id, source_system, external_employee_id, external_employee_no, status
) VALUES
(1, 1, 1, 'CSV_IMPORT', 'KOT-0001', 'NO-0001', 'ACTIVE');

INSERT INTO shift_template (
    id, tenant_id, template_code, template_name, shift_type,
    start_time, end_time, cross_day, scheduled_break_minutes, color, is_active
) VALUES
(1, 1, 'EARLY', '早番', 'WORK', '09:00:00', '18:00:00', 0, 60, 'BLUE', 1),
(2, 1, 'LATE', '遅番', 'WORK', '13:00:00', '22:00:00', 0, 60, 'ORANGE', 1),
(3, 1, 'NIGHT', '夜勤', 'WORK', '22:00:00', '07:00:00', 1, 60, 'PURPLE', 1),
(4, 1, 'HALF_AM', '半日早番', 'WORK', '09:00:00', '13:00:00', 0, 0, 'CYAN', 1),
(5, 1, 'REST', '公休', 'REST', NULL, NULL, 0, 0, 'GRAY', 1),
(6, 1, 'PAID_LEAVE', '有給', 'PAID_LEAVE', NULL, NULL, 0, 0, 'GREEN', 1);

INSERT INTO punch_source_config (
    id, tenant_id, source_system, config_name, api_base_url, api_key, api_secret, webhook_secret, enabled, config_json
) VALUES
(1, 1, 'CSV_IMPORT', 'CSV 一括取込', NULL, NULL, NULL, NULL, 1, '{"encoding":"UTF-8","timezone":"Asia/Tokyo"}'),
(2, 1, 'WEBHOOK', 'CUSTOM Webhook', 'https://example-gateway.local', 'demo-key', 'demo-secret', 'demo-hook-secret', 1, '{"mode":"push","timezone":"Asia/Tokyo"}');

INSERT INTO punch_import_batch (
    id, tenant_id, source_system, import_type, file_name, total_count, success_count, duplicate_count, unmatched_count, error_count, ignored_count, status, started_at, finished_at, created_by, created_at
) VALUES
(1, 1, 'CSV_IMPORT', 'CSV_TEXT', 'punch_may_week_1.csv', 36, 31, 0, 2, 1, 2, 'PARTIAL', TIMESTAMP '2026-05-20 09:00:00', TIMESTAMP '2026-05-20 09:02:00', 1, TIMESTAMP '2026-05-20 09:00:00'),
(2, 1, 'CSV_IMPORT', 'CSV_TEXT', 'punch_may_week_2.csv', 36, 31, 0, 2, 2, 1, 'PARTIAL', TIMESTAMP '2026-05-21 09:00:00', TIMESTAMP '2026-05-21 09:03:00', 1, TIMESTAMP '2026-05-21 09:00:00');

INSERT INTO punch_raw_log (
    id, tenant_id, employee_id, external_employee_id, source_system, source_event_id, punch_time, punch_type, device_id, device_name, raw_payload, import_batch_id, process_status, error_message, ignored_reason
) VALUES
(1001, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0001', TIMESTAMP '2026-05-01 09:07:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":1,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1002, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0002', TIMESTAMP '2026-05-02 10:14:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":2,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1003, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0003', TIMESTAMP '2026-05-03 08:21:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":3,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1004, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0004', TIMESTAMP '2026-05-04 09:28:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":4,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1005, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0005', TIMESTAMP '2026-05-05 10:35:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":5,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1006, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0006', TIMESTAMP '2026-05-06 08:42:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":6,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1007, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0007', TIMESTAMP '2026-05-07 09:49:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":7,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1008, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0008', TIMESTAMP '2026-05-08 10:56:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":8,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1009, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0009', TIMESTAMP '2026-05-09 08:03:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":9,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1010, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0010', TIMESTAMP '2026-05-10 09:10:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":10,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1011, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0011', TIMESTAMP '2026-05-11 10:17:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":11,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1012, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0012', TIMESTAMP '2026-05-12 08:24:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":12,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1013, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0013', TIMESTAMP '2026-05-13 09:31:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":13,"memo":"seed"}', 1, 'IGNORED', NULL, '管理者が検証済みのため除外'),
(1014, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0014', TIMESTAMP '2026-05-14 10:38:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":14,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1015, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0015', TIMESTAMP '2026-05-15 08:45:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":15,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1016, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0016', TIMESTAMP '2026-05-16 09:52:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":16,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1017, 1, NULL, 'EXT-UNKNOWN-017', 'CSV_IMPORT', 'evt-0017', TIMESTAMP '2026-05-17 10:59:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":17,"memo":"seed"}', 1, 'UNMATCHED', '未找到对应员工映射', NULL),
(1018, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0018', TIMESTAMP '2026-05-18 08:06:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":18,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1019, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0019', TIMESTAMP '2026-05-01 09:13:00', 'CLOCK_BAD', 'gate-04', '東京2号機', '{"row":19,"memo":"seed"}', 1, 'ERROR', 'punchType 不合法', NULL),
(1020, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0020', TIMESTAMP '2026-05-02 10:20:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":20,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1021, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0021', TIMESTAMP '2026-05-03 08:27:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":21,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1022, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0022', TIMESTAMP '2026-05-04 09:34:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":22,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1023, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0023', TIMESTAMP '2026-05-05 10:41:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":23,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1024, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0024', TIMESTAMP '2026-05-06 08:48:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":24,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1025, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0025', TIMESTAMP '2026-05-07 09:55:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":25,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1026, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0026', TIMESTAMP '2026-05-08 10:02:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":26,"memo":"seed"}', 1, 'IGNORED', NULL, '管理者が検証済みのため除外'),
(1027, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0027', TIMESTAMP '2026-05-09 08:09:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":27,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1028, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0028', TIMESTAMP '2026-05-10 09:16:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":28,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1029, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0029', TIMESTAMP '2026-05-11 10:23:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":29,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1030, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0030', TIMESTAMP '2026-05-12 08:30:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":30,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1031, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0031', TIMESTAMP '2026-05-13 09:37:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":31,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1032, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0032', TIMESTAMP '2026-05-14 10:44:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":32,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1033, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0033', TIMESTAMP '2026-05-15 08:51:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":33,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1034, 1, NULL, 'EXT-UNKNOWN-034', 'CSV_IMPORT', 'evt-0034', TIMESTAMP '2026-05-16 09:58:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":34,"memo":"seed"}', 1, 'UNMATCHED', '未找到对应员工映射', NULL),
(1035, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0035', TIMESTAMP '2026-05-17 10:05:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":35,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1036, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0036', TIMESTAMP '2026-05-18 08:12:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":36,"memo":"seed"}', 1, 'PROCESSED', NULL, NULL),
(1037, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0037', TIMESTAMP '2026-05-01 09:19:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":37,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1038, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0038', TIMESTAMP '2026-05-02 10:26:00', 'CLOCK_BAD', 'gate-03', '東京1号機', '{"row":38,"memo":"seed"}', 2, 'ERROR', 'punchType 不合法', NULL),
(1039, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0039', TIMESTAMP '2026-05-03 08:33:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":39,"memo":"seed"}', 2, 'IGNORED', NULL, '管理者が検証済みのため除外'),
(1040, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0040', TIMESTAMP '2026-05-04 09:40:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":40,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1041, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0041', TIMESTAMP '2026-05-05 10:47:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":41,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1042, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0042', TIMESTAMP '2026-05-06 08:54:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":42,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1043, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0043', TIMESTAMP '2026-05-07 09:01:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":43,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1044, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0044', TIMESTAMP '2026-05-08 10:08:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":44,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1045, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0045', TIMESTAMP '2026-05-09 08:15:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":45,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1046, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0046', TIMESTAMP '2026-05-10 09:22:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":46,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1047, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0047', TIMESTAMP '2026-05-11 10:29:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":47,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1048, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0048', TIMESTAMP '2026-05-12 08:36:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":48,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1049, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0049', TIMESTAMP '2026-05-13 09:43:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":49,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1050, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0050', TIMESTAMP '2026-05-14 10:50:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":50,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1051, 1, NULL, 'EXT-UNKNOWN-051', 'CSV_IMPORT', 'evt-0051', TIMESTAMP '2026-05-15 08:57:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":51,"memo":"seed"}', 2, 'UNMATCHED', '未找到对应员工映射', NULL),
(1052, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0052', TIMESTAMP '2026-05-16 09:04:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":52,"memo":"seed"}', 2, 'IGNORED', NULL, '管理者が検証済みのため除外'),
(1053, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0053', TIMESTAMP '2026-05-17 10:11:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":53,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1054, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0054', TIMESTAMP '2026-05-18 08:18:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":54,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1055, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0055', TIMESTAMP '2026-05-01 09:25:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":55,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1056, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0056', TIMESTAMP '2026-05-02 10:32:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":56,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1057, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0057', TIMESTAMP '2026-05-03 08:39:00', 'CLOCK_BAD', 'gate-02', '東京2号機', '{"row":57,"memo":"seed"}', 2, 'ERROR', 'punchType 不合法', NULL),
(1058, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0058', TIMESTAMP '2026-05-04 09:46:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":58,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1059, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0059', TIMESTAMP '2026-05-05 10:53:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":59,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1060, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0060', TIMESTAMP '2026-05-06 08:00:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":60,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1061, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0061', TIMESTAMP '2026-05-07 09:07:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":61,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1062, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0062', TIMESTAMP '2026-05-08 10:14:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":62,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1063, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0063', TIMESTAMP '2026-05-09 08:21:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":63,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1064, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0064', TIMESTAMP '2026-05-10 09:28:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":64,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1065, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0065', TIMESTAMP '2026-05-11 10:35:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":65,"memo":"seed"}', 2, 'IGNORED', NULL, '管理者が検証済みのため除外'),
(1066, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0066', TIMESTAMP '2026-05-12 08:42:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":66,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1067, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0067', TIMESTAMP '2026-05-13 09:49:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":67,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1068, 1, NULL, 'EXT-UNKNOWN-068', 'CSV_IMPORT', 'evt-0068', TIMESTAMP '2026-05-14 10:56:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":68,"memo":"seed"}', 2, 'UNMATCHED', '未找到对应员工映射', NULL),
(1069, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0069', TIMESTAMP '2026-05-15 08:03:00', 'CLOCK_OUT', 'gate-02', '東京2号機', '{"row":69,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1070, 1, 1, 'KOT-0001', 'WEBHOOK', 'evt-0070', TIMESTAMP '2026-05-16 09:10:00', 'CLOCK_IN', 'gate-03', '東京1号機', '{"row":70,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1071, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0071', TIMESTAMP '2026-05-17 10:17:00', 'CLOCK_OUT', 'gate-04', '東京2号機', '{"row":71,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL),
(1072, 1, 1, 'KOT-0001', 'CSV_IMPORT', 'evt-0072', TIMESTAMP '2026-05-18 08:24:00', 'CLOCK_IN', 'gate-01', '東京1号機', '{"row":72,"memo":"seed"}', 2, 'PROCESSED', NULL, NULL);
